### ISSUE TITLE
Wrong fonts appear on Mac browsers.

### ISSUE THREAD

**Issue by dhanur** [dhanur/Sunible-Beta#21]
Times New Roman appears instead of Bariol. This happens on FAQ page and Registration Page rent/own drop-down menu.

![image](https://f.cloud.github.com/assets/4460231/577103/70f9eb9c-c824-11e2-8e7b-bbc16c6549fe.png)

**Comment by ghost** [comment]
After much research and trying different styling solutions (css, optgroup, inline) I discovered that it is not possible to format drop down options and have them display consistently across all browsers for options in a select element.

"Conclusion
As noted above, it's probably better to leave styling of select boxes, optgroup and options alone and just leave them as the defaults because cross browser styling is so inconsistent it's not worth the bother."

http://www.electrictoolbox.com/style-select-optgroup-options-css/

QUESTION:  Is there a Select widget in the Pro version of Flat UI?  That may solve the problem.

Failing that, we would either have to replace the select element with a widget (which would look different) or go with a different element like a listbox (not as good as the select element for this situation).

**Comment by ghost** [comment]
I tried to replicate the select box drop down with a button in FlatUI Pro  - didn't fit the look.  I also noted that for Windows the dropdown text appeared correctly.  As this is not a functional or big aesthetic issue, bug will be closed as "do not fix".

**Comment by dhanur** [comment]
John, lets please lets keep unresolved issues open, lest we forget. Even if we don't fix them now, we have to fix them with Roman. Bad font issue on Mac is not minor (given traffic) and we have to ensure everything works on every OS (the bane of a web tech company!)

**Comment by rlytvynchuk** [comment]
fixed. moved to QA

**Comment by svlasenko** [comment]
I verified this issue in "beta" trunk
