### ISSUE TITLE
Footer Links overlaps text when resize browser window

### ISSUE THREAD

**Issue by svlasenko** [dhanur/Sunible-Beta#33]
Footer Links overlaps text on page when you resize browser 
![image](https://f.cloud.github.com/assets/1586612/732509/675ad702-e284-11e2-9ac2-14872ee71ac2.png)

**Comment by rlytvynchuk** [comment]
![scr_issue33](https://f.cloud.github.com/assets/1098812/745384/d477d7ca-e411-11e2-883c-17761b636dcf.png)

cannot reproduce. Chrome version: 27.0.1453.116 m (win), 27.0.1453.116 (mac). Please retest it after issue 27 fix applied. Scrolls display is corrupted due to vmware bug. On non-virtual machine it should be ok.

returned to QA

**Comment by svlasenko** [comment]
Verified in Master branch
