### ISSUE TITLE
Window for zip code absent on Main page

### ISSUE THREAD

**Issue by svlasenko** [dhanur/Sunible-Beta#46]
This is QA blocker and I can't test Master branch.

![image](https://f.cloud.github.com/assets/1586612/758654/5dabcec0-e746-11e2-8a09-64b9cbf7a558.png)

**Comment by ghost** [comment]
Got it.  Let me fix right now.

**Comment by ghost** [comment]
Sveta,

When I pull down either Trunk or Master, I get the following page
(attached).  The page you show was an old one that should be ignored.  The
pages.css file was modified to get rid of the uppercase font.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by svlasenko** [comment]
Hi John,

Did you update your Master branch on your local server? I still can reproduce this issue but Roman helped me with this blocker. So I localy changed in page.css file the size of text on main page. 

Please, can you look at this one more time.

Thank you,
Svetlana

**Comment by ghost** [comment]
Sveta,

I pulled down Master so my local copy now equals the origin.  I can see the
text in caps and the fix Roman implemented.

This isn't the version of the landing page on the site because we went
outside the normal QA process - please see my previous emails if needed.

I'll do a branch off of Trunk called landingPageV2 and add the code that we
are currently using.  You can merge that into Master for this week's sprint.

I  continue to work with the business team to instill good software
development practices.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```

**Comment by svlasenko** [comment]
Hi John,

Let's discuss this on meeting tomorrow.

Thank you,
Svetlana

**Comment by ghost** [comment]
OK.  You will notice a new branch off Trunk that has the current version of
the Landing Page.

John Bissell
CTO

```
        Solar Simplified

Cell:     (510) 229-0577
Skype:  john.bissell
Email:   john@sunible.com

55 Harrison Street, 3rd Floor
Oakland, CA 94607
```
